# https://taskfile.dev/usage/
version: '3'
tasks:
  default: mix test --no-start
  sh: iex --erl "-kernel shell_history enabled" -S mix run --no-start
  run: iex --erl "-kernel shell_history enabled" -S mix
  server: mix run --no-halt
  ht: curl -v http://localhost:4000